<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<!-- Main content -->
<section class="content">
    <div class="row">
    <div class="col-xs-12">
        <!-- <div class="box">
            <div class="box-body"> -->
                <div class="col-sm-5">
                    <div class="input-group">
                        <input type="text" class="form-control pull-right" size="50px;"/>       
                        <div class="input-group-addon">
                            <a href onclick="return false;"><div class="input-group-text"><i class="fa fa-check text-green"></i></div></a>
                        </div>
                    </div> 
                    
                    <div style="margin-top: 20px;">
                        <table id="tasksTable" class="ui selectable striped celled table">
                        <thead>
                        <tr>
                            <th>TASKS</th>
                            <!-- <th>Due Date</th>
                            <th>Priority</th>
                            <th>Status</th>                    
                            <th>Subtasks</th> -->
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <a href data-toggle="modal" data-target="#newModal">Complete individual evaluation for members.</a>
                                <br/>
                                <span class="text-muted">Some given description here... <a href class="text-sm">(read more)</a></span>
                            </td>
                            <!-- <td>
                                01-10-2018
                                <div class="progress progress-sm active">
                                    <div class="progress-bar progress-bar-primary progress-bar-striped" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%"></div>                            
                                </div>
                            </td>
                            <td>High</td>                    
                            <td>In Progress
                                <div class="progress progress-sm active">
                                    <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%"></div>                            
                                </div>
                            </td>
                            <td>2</td> -->
                        </tr>
                        <tr>
                            <td>
                                <a href data-toggle="modal" data-target="#newModal">Complete individual evaluation for members.</a>
                                <br/>
                                <span class="text-muted">Some given description here... <a href class="text-sm">(read more)</a></span>
                            </td>
                            <!-- <td>01-10-2018</td>
                            <td>High</td>
                            <td>In Progress</td>
                            <td>8</td> -->
                        </tr>
                        <tr>
                            <td>
                                <a href data-toggle="modal" data-target="#newModal">Complete individual evaluation for members.</a>
                                <br/>
                                <span class="text-muted">Some given description here... <a href class="text-sm">(read more)</a></span>
                            </td>
                            <!-- <td>01-10-2018</td>
                            <td>High</td>
                            <td>In Progress</td>
                            <td>5</td> -->
                        </tr>                                
                        </tbody>
                        </table>
                    </div>    
                </div>
                <div class="col-sm-7">
                    <?php include "detail.phtml" ?>
                </div>                           
            <!-- </div> -->
            <!-- /.box-body -->
        <!-- </div>         -->
    </div>
    <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->

<script>
  $(function () {
    $("#tasksTable").DataTable();
  });
</script>