<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="modal fade" id="newModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title"><i class="fa fa-flash"></i> New Task</h4>
      </div>
      <div class="modal-body">
        <!-- form start -->
        <?php
            echo $this->tag->form(
                [
                    "task/create",
                    "autocomplete" => "off",
                    "class" => "form-horizontal"
                ]
            );
        ?>
            <div class="form-group">
                <!-- <label for="fieldDetails" class="col-sm-2 control-label">Details</label> -->
                <div class="col-sm-12">
                    <?php echo $this->tag->textArea(["details", "rows" => 4, "class" => "form-control", "id" => "fieldDetails", "placeholder" => "Details"]) ?>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-xs-4">
                    <?php echo $this->tag->textField(["due_date", "size" => 30, "class" => "form-control", "id" => "fieldDueDate", "placeholder" => "Due Date"]) ?>
                </div>
                <div class="col-xs-4">
                    <?php echo $this->tag->textField(["priority_id", "type" => "number", "class" => "form-control", "id" => "fieldPriorityId", "placeholder" => "Priority"]) ?>
                </div>
            </div>

            <div class="box box-primary">
                <div class="box-header">
                <h3 class="box-title">Date picker</h3>
                </div>
                <div class="box-body">
                <!-- Date -->
                <div class="form-group">
                    <label>Date:</label>

                    <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" class="form-control pull-right" id="datepicker">
                    </div>
                    <!-- /.input group -->
                </div>
                <!-- /.form group -->        
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-primary">Save & New</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>