<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="modal fade" id="newModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title"><i class="fa fa-flag"></i> New Task</h4>
      </div>
      <div class="modal-body">
        <!-- form start -->
        <?php
            echo $this->tag->form(
                [
                    "task/create",
                    "autocomplete" => "off",
                    "class" => "form-horizontal"
                ]
            );
        ?>
            <div class="form-group">
                <!-- <label for="fieldDetails" class="col-sm-2 control-label">Details</label> -->
                <div class="col-sm-12">
                    <?php echo $this->tag->textArea(["details", "rows" => 1, "class" => "form-control", "id" => "fieldDetails", "placeholder" => "Details"]) ?>
                </div>
            </div>
            
            <div class="form-group">              
                <div class="col-xs-4">      
                    <!-- <?php echo $this->tag->textField(["due_date", "size" => 30, "class" => "form-control", "id" => "fieldDueDate", "placeholder" => "Due Date"]) ?> -->
                    <div class="input-group date">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <input type="text" class="form-control pull-right" id="datepicker" placeholder="Due Date">
                    </div>                               
                </div>   
                <div class="col-xs-4">                                 
                    <!-- <?php echo $this->tag->textField(["priority_id", "type" => "number", "class" => "form-control", "id" => "fieldPriorityId", "placeholder" => "Priority"]) ?> -->
                    <div class="dropdown">
                        <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">Priority
                        <span class="caret"></span></button>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">High</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Medium</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Low</a></li>
                        </ul>
                    </div>
                </div> 
            </div>                
        </form>

        <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">People</h3>
              <a href class="pull-right"><i class="fa fa-plus"></i></a>
            </div>
            <div class="box-body">
                <div class="user-block">
                    <img class="img-circle" src="/admin-lte/dist/img/user1-128x128.jpg" alt="User Image">
                    <span class="username"><a href="#">Jonathan Burke Jr.</a></span>
                    <span class="description">Owner<a href class="btn btn-default btn-xs" style="margin-left: 10px;">Transfer</a></span> 
                </div>
            </div>
        </div> 
        
        <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Subtasks</h3>
              <a href class="pull-right"><i class="fa fa-plus"></i></a>
            </div>
            <div class="box-body">
                <span class="text-muted">No Subtasks defined for this task.</span>
            </div>
        </div>    

        <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Related content</h3>
              <a href class="pull-right"><i class="fa fa-plus"></i></a>
            </div>
            <div class="box-body">
                <span class="text-muted">No related content attached for this task.</span>
            </div>
        </div>  

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-primary">Save & New</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
  $(function () {
    $('#datepicker').datepicker({
        autoclose: true
    });
  });
</script>    