<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["task", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create task
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "task/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldDetails" class="col-sm-2 control-label">Details</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["details", "size" => 30, "class" => "form-control", "id" => "fieldDetails"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDueDate" class="col-sm-2 control-label">Due Of Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["due_date", "size" => 30, "class" => "form-control", "id" => "fieldDueDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPriorityId" class="col-sm-2 control-label">Priority</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["priority_id", "type" => "number", "class" => "form-control", "id" => "fieldPriorityId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldParentTaskId" class="col-sm-2 control-label">Parent Of Task</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["parent_task_id", "type" => "number", "class" => "form-control", "id" => "fieldParentTaskId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateCreated" class="col-sm-2 control-label">Date Of Created</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["date_created", "size" => 30, "class" => "form-control", "id" => "fieldDateCreated"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatedBy" class="col-sm-2 control-label">Created Of By</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["created_by", "type" => "number", "class" => "form-control", "id" => "fieldCreatedBy"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>