<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user_info/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["user_info/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Username</th>
            <th>First Of Name</th>
            <th>Last Of Name</th>
            <th>Job Of Title</th>
            <th>Location</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Skype</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user_info): ?>
            <tr>
                <td><?php echo $user_info->username ?></td>
            <td><?php echo $user_info->first_name ?></td>
            <td><?php echo $user_info->last_name ?></td>
            <td><?php echo $user_info->job_title ?></td>
            <td><?php echo $user_info->location ?></td>
            <td><?php echo $user_info->email ?></td>
            <td><?php echo $user_info->phone ?></td>
            <td><?php echo $user_info->skype ?></td>

                <td><?php echo $this->tag->linkTo(["user_info/edit/" . $user_info->username, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["user_info/delete/" . $user_info->username, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("user_info/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("user_info/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("user_info/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("user_info/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
