<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="modal fade" id="newModal">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title"><i class="fa fa-user"></i> New User</h4>
        </div>
        <div class="modal-body">
            <!-- form start -->
            <?php
                echo $this->tag->form(
                    [
                        "task/create",
                        "autocomplete" => "off",
                        "class" => "form-horizontal"
                    ]
                );
            ?>

                            
            </form>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary">Save</button>
            <button type="button" class="btn btn-primary">Save & New</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
    </div>
  </div>
</div>

<div class="modal fade" id="relatedContentModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"><i class="fa fa-file"></i> Add related content</h4>
            </div>
            <div class="modal-body">
            </div>    
        <div>
    </div> 
</div>           

<script>
  $(function () {
    
    $('#datepicker').datepicker({
        autoclose: true
    });

    $('#subtask').keypress(function (e) {
        if (e.which == 13) {
            $('#subtaskToggler').fadeIn();
            $('#subtask').fadeOut();
            $('#subtask').val('');
        }
    });

  });
  
  function toggleAddSubtask() {
    $('#subtaskToggler').fadeOut();  
    $('#subtask').fadeIn();
    $('#subtask').focus();
  }
</script>    