<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1><i class="user icon"></i>Edit User '<?php echo $username ?>'</h1>
        <div class="ui breadcrumb">
            <a href="/AgileDev/users" class="section">Users</a>
            <div class="divider"> / </div>
            <div class="active section">Edit</div>
        </div>
    </section>

    <div class="ui divider"></div>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">                                                   

                <?php include "messages.phtml" ?>  
                <?php include "form.phtml" ?>

            </div>
        </div>
    </div> 

</div>    