<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <i class="fa fa-users"></i> Users
      <button class="ui primary small button" style="margin-right: 0px;" data-toggle="modal" data-target="#infoModal"><i class="fa fa-plus"></i> New User</button>
      <a href="/AgileDev/users/new" class="ui primary small button"><i class="fa fa-plus"></i> New User 2</a>
    </h1>
    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Users</li>      
    </ol>
  </section>

  <?php include "list.phtml" ?>
  <?php include "details_modal.phtml" ?>

</div>  
