<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <i class="fa fa-users"></i> Users
      <button class="btn btn-primary" style="margin-right: 0px;" data-toggle="modal" data-target="#newModal"><i class="fa fa-plus"></i> New User</button>
    </h1>
    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Users</li>      
    </ol>
  </section>
  
  <?php include "list.phtml" ?>
  <?php include "details_modal.phtml" ?>

</div>    