<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">

            <?php include "messages.phtml" ?>
        
            <table id="tasksTable" class="ui selectable striped celled table" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>USER ID</th>
                    <th>FIRST NAME</th>
                    <th>LAST NAME</th>
                    <th>JOB TITLE</th>
                    <th>LOCATION</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($users as $user): ?>
                <tr>
                    <td><?php echo $user->username ?></td>
                    <td>Jeffrey</td>
                    <td>Pogoy</td>
                    <td>Solutions Development Manager</td>
                    <td>Kingston</td>
                </tr>
            <?php endforeach; ?>
            <tbody>
            </table>
        </div>
    </div>
</section>

<script>
  $(function () {
    $("#tasksTable").DataTable();
  });
</script>