<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
        <i class="fa fa-user"></i> New User
        </h1>
        <ol class="breadcrumb">
        <li><a href="/AgileDev"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/AgileDev/users"><i class="fa fa-users"></i> Users</a></li>   
        <li class="active">New User</li>   
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <?php echo $this->getContent(); ?>

                <?php
                    echo $this->tag->form(
                        [
                            "users/create",
                            "autocomplete" => "off",
                            "class" => "ui form"
                        ]
                    );
                ?>
                

                <div class="ui raised segment">    
                    <div class="inline fields">
                        <div class="four wide field">
                            <label for="fieldUsername" class="col-sm-2 control-label">Username</label>
                            <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
                        </div>                           
                    </div>                    
                
                    <div class="inline fields">
                        <div class="four wide field">
                            <button type="submit" class="ui primary small button">Save</button>
                            <button type="button" class="ui secondary small button">Save & New</button>
                            <button type="button" class="ui small button">Cancel</button>
                            <!-- <a href="/AgileDev/users" class="ui button" >Cancel</a> -->
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </div>  
</div>

<script src="/AgileDev/public/js/users.js"></script>    