<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
        <i class="fa fa-user"></i> New User
        </h1>
        <ol class="breadcrumb">
        <li><a href="/AgileDev"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/AgileDev/users"><i class="fa fa-users"></i> Users</a></li>   
        <li class="active">New User</li>   
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <?php echo $this->getContent(); ?>

                <?php
                    echo $this->tag->form(
                        [
                            "users/create",
                            "autocomplete" => "off",
                            "class" => "form-horizontal"
                        ]
                    );
                ?>
                
                <div class="box">
                    <div class="box-header with-border">
                        <!-- <h3 class="box-title">System Credentials</h3> -->
                    </div>
                    <div class="box-body">
                        <div class="form-group required">
                            <label for="fieldUsername" class="col-sm-2 control-label">Username</label>
                            <div class="col-sm-2">
                                <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
                            </div>
                        </div>

                        <div class="form-group required">
                            <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
                            <div class="col-sm-3">
                                <?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="fieldPassword" class="col-sm-2 control-label">Confirm Password</label>
                            <div class="col-sm-3">
                                <?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "fieldConfirmPassword"]) ?>
                            </div>
                        </div>
                    <!-- </div>
                </div>    

                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Personal Information</h3>
                    </div>
                    <div class="box-body"> -->
                        <div class="form-group">
                            <label for="fieldFirstName" class="col-sm-2 control-label">First Name</label>
                            <div class="col-sm-3">
                                <?php echo $this->tag->textField(["first_name", "size" => 30, "class" => "form-control", "id" => "fieldFirstName"]) ?>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="fieldLastName" class="col-sm-2 control-label">Last Name</label>
                            <div class="col-sm-3">
                                <?php echo $this->tag->textField(["last_name", "size" => 30, "class" => "form-control", "id" => "fieldLastName"]) ?>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="fieldJobTitle" class="col-sm-2 control-label">Job Title</label>
                            <div class="col-sm-3">
                                <?php echo $this->tag->textField(["job_title", "size" => 30, "class" => "form-control", "id" => "fieldJobTitle"]) ?>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="fieldLocation" class="col-sm-2 control-label">Location</label>
                            <div class="col-sm-3">
                                <?php echo $this->tag->textField(["location", "size" => 30, "class" => "form-control", "id" => "fieldLocation"]) ?>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
                            <div class="col-sm-3">
                                <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="fieldPhone" class="col-sm-2 control-label">Phone</label>
                            <div class="col-sm-3">
                                <?php echo $this->tag->textField(["phone", "size" => 30, "class" => "form-control", "id" => "fieldPhone"]) ?>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="fieldSkype" class="col-sm-2 control-label">Skype</label>
                            <div class="col-sm-3">
                                <?php echo $this->tag->textField(["skype", "size" => 30, "class" => "form-control", "id" => "fieldSkype"]) ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Save</button>
                                <button type="button" class="btn btn-primary">Save & New</button>
                                <a href="/AgileDev/users" class="btn btn-default" >Cancel</a>
                            </div>    
                        </div>

                    </div>
                </div>      
            </div>
        </div>
    </div>  
</div>

<script src="/AgileDev/public/js/users.js"></script>    