<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1><i class="user icon"></i>New user</h1>
        <div class="ui breadcrumb">
            <a href="/AgileDev/users" class="section">Users</a>
            <div class="divider"> / </div>
            <div class="active section">New</div>
        </div>
    </section>

    <div class="ui divider"></div>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">                                                   

                <?php include "messages.phtml" ?>

                <?php
                    echo $this->tag->form(
                        [
                            "users/create",
                            "autocomplete" => "off",
                            "class" => "ui form",
                            "id" => "newForm"
                        ]
                    );
                ?>
                    
                    <h4 class="ui dividing header">System Identification</h4>
                    <div class="fields">
                        <div class="small required field">
                            <label for="fieldUsername">User ID</label>
                            <?php echo $this->tag->textField(["username", "id" => "fieldUsername"]) ?>
                        </div>
                        <div class="small required field">
                            <label for="fieldPassword">Password</label>
                            <?php echo $this->tag->passwordField(["password", "id" => "fieldPassword"]) ?>
                        </div>
                        <div class="small field">
                            <label for="">Confirm Password</label>
                            <input type="password" id="fieldConfirmPassword">
                        </div>
                    </div>
                    
                    <h4 class="ui dividing header">Personal Information</h4>
                    <div class="fields">
                        <div class="small four wide field">
                            <label for="">First Name</label>
                            <input type="text">
                        </div>
                        <div class="small four wide field">
                            <label for="">Middle Name</label>
                            <input type="text">
                        </div>
                        <div class="small four wide field">
                            <label for="">Last Name</label>
                            <input type="text">
                        </div>
                    </div>
                    <div class="fields">
                        <div class="small four wide field">
                            <label for="">Job Title</label>
                            <input type="text">
                        </div>
                        <div class="small four wide field">
                            <label for="">Location</label>
                            <input type="text">
                        </div>
                        <div class="small four wide field">
                            <label for="">Email</label>
                            <input type="text">
                        </div>
                    </div>
                    <div class="fields">
                        <div class="small field">
                            <label for="">Phone</label>
                            <input type="text">
                        </div>
                        <div class="small field">
                            <label for="">Skype</label>
                            <input type="text">
                        </div>
                    </div>

                    <div class="ui error message"></div>
                    
                    <div class="ui small primary submit button">Save</div>
                    <div class="ui small teal submit button">Save & New</div>
                    <div class="ui small reset button">Reset</div>
                    <a href="/AgileDev/users" class="ui small button">Cancel</a>                    
            
                <?php echo $this->tag->endForm(); ?>    

            </div>
        </div>
    </div>  
</div>

<script src="/AgileDev/public/js/users_new.js"></script>