<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1><i class="users icon"></i>Search</h1>
    <div class="ui breadcrumb">
      <a href="/AgileDev/users/new" class="ui tiny primary button"><i class="plus icon"></i>New User</a>
    </div>  
  </section>

  <div class="ui divider"></div>

  <?php include "messages.phtml" ?>

</div>