<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

?>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1><i class="fa fa-puzzle-piece"></i> Edit Project '<?php echo $name ?>'</h1>
        <div class="ui breadcrumb">
            <a href="/AgileDev/projects" class="section">Projects</a>
            <div class="divider"> / </div>
            <div class="active section">New</div>
        </div>
    </section>

    <div class="ui divider"></div>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">                                                   

                <?php include "messages.phtml" ?>  
                
                <?php

                    echo $this->tag->form(
                        [
                            "projects/save",
                            "autocomplete" => "off",
                            "class" => "ui form",
                            "id" => "dataForm"
                        ]
                    );
                ?>

                <div class="required field">
                    <label for="">Name</label>
                    <?php echo $this->tag->textField(["name", "id" => "fieldName"]) ?>
                </div>
                <div class="field">
                    <label for="">Description</label>
                    <?php echo $this->tag->textArea(["description", "id" => "fieldDescription"]) ?>
                </div>

                <div class="ui error message"></div>
    
                <?php                    
                    echo '<div class="ui small primary submit button">Save Changes</div>
                        <a href="/AgileDev/projects" class="ui button">Cancel</a>';
                ?>    
            
                <?php echo $this->tag->hiddenField("id") ?>    

                <?php echo $this->tag->endForm(); ?>
            </div>
        </div>
    </div> 
     
</div>
  
<script src="/AgileDev/public/js/project_form.js"></script>