<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1><i class="fa fa-puzzle-piece"></i> Projects</h1>
    <div class="ui breadcrumb">
      <a href="/AgileDev/projects/new" class="ui tiny primary button"><i class="plus icon"></i>New Project</a>
    </div>  
    <!-- <button class="btn btn-primary" style="margin-right: 0px;" data-toggle="modal" data-target="#newModal"><i class="fa fa-plus"></i> New Project</button> -->
    <!-- <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-puzzle-piece"></i> Home</a></li>
      <li class="active">Projects</li>      
    </ol>-->
  </section>
  
  <div class="ui divider"></div>

  <?php include "list.phtml" ?>

</div>    