<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <i class="fa fa-puzzle-piece"></i> Projects
    </h1>
    <div class="ui breadcrumb">
      <a href="/AgileDev/projects/new" class="ui tiny primary button"><i class="plus icon"></i>New Project</a>
    </div>  
  </section>
  
  <div class="ui divider"></div>

  <?php include "list.phtml" ?>

</div>    