<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            
            <form class="ui form">
                <div class="inline fields">
                    <div class="five wide field">
                        <input type="text" placeholder="Type in keywords...">
                    </div>
                    <div class="eleven wide field">
                        <div class="ui teal button">Search</div>
                        <button class="ui button" type="reset">Reset</button>
                    </div>                
                </div>
            </form>
           
            <table class="ui celled striped table">
                <thead class="full-width">
                    <tr>
                        <th>NAME</th>
                        <th>DESCRIPTION</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($page->items as $item): ?>
                        <tr>
                            <td>
                                <a href="projects/edit/<?php echo $item->id ?>" data-tooltip="Click to view profile" data-position="right center">
                                    <?php echo $item->name ?>
                                </a>
                            </td>
                            <td><?php echo $item->description ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="3">
                            <div class="ui equal width grid">
                                <div class="column">
                                    <div class="common-text">
                                        <?php echo "Page ", $page->current, " of ", $page->total_pages, ". Showing Records ", $start, " - ", $end, " of ", $totalItems, "." ?>
                                    </div>
                                </div>
                                <div class="column">
                                    <div class="ui right floated pagination menu">
                                        <a href="projects?page=<?= $page->first; ?>" class="icon item <?php echo $page->current == 1 ? 'disabled':''?>">
                                            <i class="angle double left icon"></i>
                                        </a>
                                        <a href="projects?page=<?= $page->before; ?>" class="icon item <?php echo $page->current == 1 ? 'disabled':''?>">
                                            <i class="angle left icon"></i>
                                        </a>         
                                                      
                                        <?php for ($p = 1; $p <= $page->total_pages; $p++): ?>
                                            <a href="projects?page=<?php echo $p ?>" class="item <?php echo $page->current == $p ? 'active':''?>"><?php echo $p ?></a>
                                        <?php endfor; ?>
                                                                     
                                        <a href="projects?page=<?= $page->next; ?>" class="icon item <?php echo $page->current == $page->last ? 'disabled':''?>">
                                            <i class="angle right icon"></i>
                                        </a>
                                        <a href="projects?page=<?= $page->last; ?>" class="icon item <?php echo $page->current == $page->last ? 'disabled':''?>">
                                            <i class="angle double right icon"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>                                                        
                        </th>
                    </tr>
                </tfoot>
            </table>                        
            
        </div>
    </div>
</section>

<script>
  $(function () {
    $("#projectTable").DataTable();
  });
</script>