<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <table id="projectTable" class="ui selectable striped celled table">
            <thead>
            <tr>
                <th>NAME</th>
                <th>DESCRIPTION</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($projects as $project): ?>
                <tr>
                    <td>
                        <a href="projects/edit/<?php echo $project->id ?>" data-tooltip="Click to view profile" data-position="right center">
                            <?php echo $project->name ?>
                        </a>
                    </td>
                    <td><?php echo $project->description ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
            </table>
        </div>
    </div>
</section>

<script>
  $(function () {
    $("#projectTable").DataTable();
  });
</script>