<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            
            <?php
                echo $this->tag->form(
                    [
                        "projects",
                        "autocomplete" => "off",
                        "class" => "ui form",
                        "id" => "searchForm"
                    ]
                );                
            ?>
                <!-- <div class="inline fields">
                    <div class="five wide field">
                        <?php echo $this->tag->textField(["keyword", "id" => "fieldKeyword", "placeholder" => "Type in keywords..."]) ?>
                    </div>
                    <div class="field">
                        <div class="ui teal submit button">Search</div>
                        <button class="ui button" type="reset" id="resetBtn">Reset</button>
                    </div>                
                </div> -->

            <div class="ui action left icon input">
                <i class="search icon"></i>
                <?php echo $this->tag->textField(["keyword", "id" => "fieldKeyword", "placeholder" => "Search", "value" => $keyword]) ?>
                <button class="ui teal submit button">Submit</button>
            </div>            

            <?php echo $this->tag->endForm(); ?>
            
            <form id="sortForm" action="projects" method="post">
            
                <?php echo $this->tag->textField(["sortField", "id" => "sortField", "value" => $sortField]) ?>
                <?php echo $this->tag->textField(["sortDirection", "id" => "sortDirection", "value" => $sortDirection]) ?>       
            
            </form>    

            <table class="ui sortable selectable celled striped table">
                <thead class="full-width">
                    <tr>
                        <th class="five wide <?php echo $sortField == 'name' ? 'sorted' . ($sortDirection == 'DESC' ? ' descending' : ' ascending') : '' ?>" onclick="sort('name', <?php echo 'DESC' ?>);">NAME</th>
                        <th class="ten wide <?php echo $sortField == 'description' ? 'sorted' . ($sortDirection == 'DESC' ? ' descending' : ' ascending') : '' ?>" onclick="sort('description', <?php echo $sortDirection == 'DESC' ? ' ASC' : ' DESC' ?>);">DESCRIPTION</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($page->items as $item): ?>
                        <tr>
                            <td>
                                <a href="projects/edit/<?php echo $item->id ?>" data-tooltip="Click to view profile" data-position="right center">
                                    <?php echo $item->name ?>
                                </a>
                            </td>
                            <td><?php echo $item->description ?></td>
                            <td>
                                <a href onclick="del('<?php echo $item->id ?>', '<?php echo $item->name ?>'); return false;" data-tooltip="Delete this project" data-position="bottom center">
                                    <i class="trash outline red icon"></i>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="3">
                            <div class="ui equal width grid">
                                <div class="column">
                                    <div class="common-text">
                                        <?php 
                                        
                                            if (count($page->items) > 0) {
                                                echo "Page ", $page->current, " of ", $page->total_pages, ". Showing Records ", $start, " - ", $end, " of ", $totalItems, ".";
                                            } else {
                                                echo "No projects to show...";
                                            }    
                                        
                                        ?>
                                    </div>
                                </div>
                                <div class="column">
                                    <div class="ui right floated pagination menu" style="display: <?php echo count($page->items) > 0 ? '' : 'none' ?>">
                                        <a href="projects?page=<?= $page->first; ?>" class="icon item <?php echo $page->current == 1 ? 'disabled':''?>">
                                            <i class="angle double left icon"></i>
                                        </a>
                                        <a href="projects?page=<?= $page->before; ?>" class="icon item <?php echo $page->current == 1 ? 'disabled':''?>">
                                            <i class="angle left icon"></i>
                                        </a>         
                                                      
                                        <?php for ($p = 0; $p <= count($pages); $p++): ?>
                                            <?php if (strlen($pages[$p]) > 0): ?>
                                                <?php if ($pages[$p] != '...'): ?>
                                                    <a href="projects?page=<?php echo $pages[$p] ?>" class="item <?php echo $page->current == $pages[$p] ? 'active':''?>">
                                                        <?php echo $pages[$p] ?>
                                                    </a>
                                                <?php else: ?>    
                                                    <div class="item">
                                                        <?php echo $pages[$p] ?>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>    
                                        <?php endfor; ?>
                                                                     
                                        <a href="projects?page=<?= $page->next; ?>" class="icon item <?php echo $page->current == $page->last ? 'disabled':''?>">
                                            <i class="angle right icon"></i>
                                        </a>
                                        <a href="projects?page=<?= $page->last; ?>" class="icon item <?php echo $page->current == $page->last ? 'disabled':''?>">
                                            <i class="angle double right icon"></i>
                                        </a>
                                    </div>                                    
                                </div>
                            </div>                                                        
                        </th>
                    </tr>
                </tfoot>
            </table>                        
            
        </div>
    </div>
</section>

<div class="ui tiny modal delete">
    <i class="close icon"></i>
    <div class="header">
        <i class="trash outline icon"></i> Delete Project
    </div>
    <div class="content custom-text" style="min-height: 30px;">        
    </div>
    <div class="actions">
        <div class="ui negative button">Cancel</div>
        <div class="ui positive button">OK</div>
    </div>
</div>

<div class="ui active loader"></div>

<script src="/AgileDev/public/js/project_list.js"></script>        
