<?php 
  
    if (strlen($this->getContent()) > 0) {
        echo "<script type=\"text/javascript\">
            new PNotify({
            title: 'Agile Developer',
            text: '" . addslashes($this->getContent()) . "',
            type: 'error',
            nonblock: true,
            delay: 5000,
            hide: true,
            addclass: 'stack-modal'
            });
            </script>"; 
    } 

   
    $messages = $this->flashSession->getMessages();
    if (!is_null($messages)) {
        foreach ($messages as $type => $message) {
            foreach ($messages as $type => $message) {
                
                switch ($type) {
                case 'success':
                    
                    echo "<script type=\"text/javascript\">
                        new PNotify({
                            title: 'Success',
                            text: '" . $message[0] . "',
                            type: 'success',
                            nonblock: true,
                            delay: 3000,
                            hide: true,
                            addclass: 'stack-modal'
                        });
                        </script>";

                    break;
                
                case 'error':
                    
                    echo "<script type=\"text/javascript\">
                            new PNotify({
                            title: 'Error',
                            text: '" . $message[0] . "',
                            type: 'error',
                            nonblock: true,
                            delay: 3000,
                            hide: true,
                            addclass: 'stack-modal'
                            });
                            </script>";        

                    break;

                case 'warning':
                    
                    echo "<script type=\"text/javascript\">
                            new PNotify({
                                title: 'Warning',
                                text: '" . $message[0] . "',
                                type: 'warning',
                                nonblock: true,
                                delay: 3000,
                                hide: true,
                                addclass: 'stack-modal'
                            });
                            </script>"; 
                    
                    break;  

                default: # Notice
                    
                    echo "<script type=\"text/javascript\">
                            new PNotify({
                                title: 'Info',
                                text: '" . $message[0] . "',
                                type: 'info',
                                nonblock: true,
                                delay: 3000,
                                hide: true,
                                addclass: 'stack-modal'
                            });
                            </script>"; 

                    break;
                }
                
                break;
            }  
        }  
    }
    
?>