<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1><i class="block layout icon"></i> <?php echo $project->name ?></h1>
        <div class="ui breadcrumb">
            <a href="/AgileDev/projects" class="section">Projects</a>
            <div class="divider"> / </div>
            <div class="active section"><?php echo $project->name ?></div>
        </div>
    </section>

    <div class="ui divider"></div>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">    



            </div>
        </div>
    </div>
</div>