<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search user
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["user/new", "Create user"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "user/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateCreated" class="col-sm-2 control-label">Date Of Created</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["date_created", "size" => 30, "class" => "form-control", "id" => "fieldDateCreated"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastLogin" class="col-sm-2 control-label">Last Of Login</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["last_login", "size" => 30, "class" => "form-control", "id" => "fieldLastLogin"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
