<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <i class="hand paper outline icon"></i>Roles
    </h1>
    <div class="ui breadcrumb">
      <a href="/AgileDev/roles/new" class="ui tiny primary button"><i class="plus icon"></i>New Role</a>
    </div> 
  </section>
  
  <div class="ui divider"></div>

  <?php include "list.phtml" ?>

</div>    