<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
            <img src="admin-lte/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
            <p>Alexander Pierce</p>
            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION
            <li class="<?php echo $this->session->get('active_menu') == 'dashboard' ? 'active' : '' ?>">
                <a href="/dashboard"><i class="fa fa-dashboard"></i><span>Dashboard</span></a>
            </li>     
            <li class="<?php echo $this->session->get('active_menu') == 'projects' ? 'active' : '' ?>">
                <a href="/projects"><i class="fa fa-puzzle-piece"></i>
                    <span>Projects</span>
                    <span class="pull-right-container">
                        <span class="label label-primary pull-right">4</span>
                    </span>
                </a>
            </li>                            
            <li class="<?php echo $this->session->get('active_menu') == 'inbox' ? 'active' : '' ?>">
                <a href="/inbox"><i class="fa fa-inbox"></i>
                    <span>Inbox</span>
                    <span class="pull-right-container">
                        <span class="label label-primary pull-right">4</span>
                    </span>
                </a>
            </li>    
            <li class="<?php echo $this->session->get('active_menu') == 'my_tasks' ? 'active' : '' ?>">
                <a href="/my_tasks"><i class="fa fa-flag-o"></i> 
                    <span>My Tasks</span>
                    <span class="pull-right-container">
                        <span class="label label-primary pull-right">4</span>
                    </span>
                </a>
            </li>
            <li class="<?php echo $this->session->get('active_menu') == 'queued' ? 'active' : '' ?>">
                <a href="/queued">
                    <i class="fa fa-history"></i>
                    <span>Queued</span>
                    <span class="pull-right-container">
                        <span class="label label-primary pull-right">4</span>
                    </span>
                </a>
            </li>
            <li class="<?php echo $this->session->get('active_menu') == 'involved' ? 'active' : '' ?>">
                <a href="/involved">
                    <i class="fa fa-star-half-empty"></i>
                    <span>Involved</span>
                    <span class="pull-right-container">
                        <span class="label label-primary pull-right">4</span>
                    </span>
                </a>
            </li>
            <li class="<?php echo $this->session->get('active_menu') == 'archived' ? 'active' : '' ?>">
                <a href="/archived">
                    <i class="fa fa-suitcase"></i>
                    <span>Archived</span>
                    <span class="pull-right-container">
                        <span class="label label-primary pull-right">3</span>
                    </span>
                </a>
            </li>                                                    
            <li class="<?php echo $this->session->get('active_menu') == 'syslogs' ||
            $this->session->get('active_menu') == 'users' ||
            $this->session->get('active_menu') == 'roles' ? 'treeview active' : 'treeview' ?>">
                <a href="#">
                    <i class="fa fa-cogs"></i> <span>Administration</span>
                    <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>                
                <ul class="treeview-menu">
                    <li class="<?php echo $this->session->get('active_menu') == 'users' ? 'active' : '' ?>">
                        <a href="/users"><i class="fa fa-user"></i> <span>Users</span></a>
                    </li>
                    <li class="<?php echo $this->session->get('active_menu') == 'roles' ? 'active' : '' ?>">
                        <a href="/roles"><i class="fa fa-hand-paper-o"></i> <span>Roles</span></a>
                    </li>
                    <li class="<?php echo $this->session->get('active_menu') == 'syslogs' ? 'active' : '' ?>">
                        <a href="/syslogs"><i class="fa fa-book"></i> <span>System Logs</span></a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-copy"></i> <span>Reports</span>
                    <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>                
                <ul class="treeview-menu">
                    <li>
                        <a href="/users"><i class="fa fa-user"></i> <span>Report 1</span></a>
                    </li>
                    <li>
                        <a href="/users"><i class="fa fa-user"></i> <span>Report 2</span></a>
                    </li>
                    <li>
                        <a href="/users"><i class="fa fa-user"></i> <span>Report 3</span></a>
                    </li>
                </ul>
            </li>  
        </ul>        
    </section>
    <!-- /.sidebar -->
  </aside>

